# Generated by Django 2.1.8 on 2019-08-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alertname', models.CharField(max_length=100)),
                ('instance', models.CharField(max_length=50)),
                ('job', models.CharField(max_length=30)),
                ('monitor', models.CharField(max_length=30)),
                ('severity', models.CharField(max_length=30)),
                ('startsAt', models.DateTimeField()),
                ('endsAt', models.DateTimeField()),
                ('receiver', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=10)),
                ('post_times', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'alert_info',
            },
        ),
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('receiver', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('dingding_robot_api', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'receiver',
            },
        ),
    ]
