# Generated by Django 2.1.8 on 2019-08-21 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiver',
            name='dingding_robot_api',
            field=models.CharField(max_length=200),
        ),
    ]
