{
 "title": "alert",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "key_word",
    "query": "select COLUMN_NAME from information_schema.COLUMNS where table_name = 'alert';"
   }
  ]
 },
 "panels": [
  {
   "title": " 告警 TOP 10  -  $key_word",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select $key_word,count(*) from alert group by  $key_word  order by count(*) limit 10;"
    }
   ]
  },
  {
   "title": "firing alert",
   "type": "table",
   "gridPos": { "h": 12, "w": 16, "x": 8, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT id,alertname,instance,job,startsAt,receiver,post_times from alert where status='firing';"
    }
   ]
  },
  {
   "title": "recent 100 alert",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT id,alertname,instance,job,status,startsAt,endsAt,receiver,post_times from alert order by id desc limit 100;"
    }
   ]
  }
 ]
}